### Pandas

Pandas is an open source, BSD-Licensed library providing high-performance, easy-to-use data structure and data analysis tools for the Python programming language.

-> What is Data Frames?
-> What is Data Series?
-> Different operations in Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.DataFrame(np.arange(0,20).reshape(5,4), index=['Row1','Row2','Row3','Row4','Row5'], columns=['Column1','Column2','Column3','Column4'])

In [3]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [4]:
# Accessing the elements
# 1 .loc      2  .iloc

df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int32

In [5]:
type(df.loc['Row1'])                # series means either one row or one column

pandas.core.series.Series

In [6]:
df.iloc[:,:]                   # :,: means all the rows and all the columns

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [7]:
df.iloc[0:2,1:3]

Column2  Column3
Row1        1        2
Row2        5        6

In [8]:
type(df.iloc[:,:])            # DataFrame has atleast more than one row and more than one column

pandas.core.frame.DataFrame

In [9]:
# Converting DataFrames into array

df.iloc[:,1:].values         # It will remove row name and column name

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [10]:
df.iloc[:,1:].values.shape

(5, 3)

In [11]:
df.isnull()            # Check if any value is null

Column1  Column2  Column3  Column4
Row1    False    False    False    False
Row2    False    False    False    False
Row3    False    False    False    False
Row4    False    False    False    False
Row5    False    False    False    False

In [12]:
df.isnull().sum()       # How many null values are there in each column

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [13]:
df['Column1'].value_counts()       # How many times each values is present

0     1
4     1
8     1
12    1
16    1
Name: Column1, dtype: int64

In [14]:
df['Column1'].unique()        # If any value is repeated, it will not show in array

array([ 0,  4,  8, 12, 16])

In [15]:
df['Column3']       # We can directly use this instead of using .loc function

Row1     2
Row2     6
Row3    10
Row4    14
Row5    18
Name: Column3, dtype: int32

In [16]:
type(df['Column2'])

pandas.core.series.Series

In [17]:
df[['Column1','Column3']]          # Put column name in list

Column1  Column3
Row1        0        2
Row2        4        6
Row3        8       10
Row4       12       14
Row5       16       18

In [20]:
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])